#!/bin/bash
NB_PROCS=$1
NODES=$IOR_NODES
CONNECTOR=$2
LOG_FILE_NAME=$IOR_JOB_ID

mpirun -np $NB_PROCS --hostfile $NODES --mca plm_rsh_agent "$CONNECTOR" IOR -a MPIIO -t 1024K -b 1G -F -o /mnt/dfs/$LOG_FILE_NAME